name: hello-world
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  job-hello:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo 'Hello world'