# .github/workflows/pr-agent.yml
name: PR Agent
on:
  workflow_run:
    workflows: ["Lint PR"]
    types:
        - completed
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' && github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    
    steps:
    - name: PR Agent action step
      uses: the-pr-agent/pr-agent@main
      env:
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        pr_reviewer.extra_instructions: "Focus on Next.js and typescript best practices, type hints, and documentation."